name: Pull Request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  pull-request:
    uses: nozomiishii/workflows/.github/workflows/pull-request.yaml@ec605e0a4f2acdb21166f3b430dd9345dd4dca2b # v1.1.0
