name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  static:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read # required by actions/checkout to fetch repository code

    steps:
      - name: Get code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Format Check
        run: pnpm format

      - name: Lint
        run: pnpm validate

  required:
    needs: [static]
    if: always()
    runs-on: ubuntu-slim
    timeout-minutes: 1
    steps:
      - name: Fail if any required job failed or was cancelled
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "A required job failed or was cancelled"
          exit 1
